const mongoose = require("mongoose");

// Transaction schema
const txnSchema = new mongoose.Schema(
  {
    client: String,
    amount: {
      type: Number,
      required: [true, "Amount is required"],
    },
    currency: {
      type: String,
      required: [true, "Currency is required"],
      enum: {
        values: ["ETB", "USD", "AED", "EURO"],
        message: "Currency must be one of: ETB, USD, AED, EURO",
      },
    },
    cause: {
      type: String,
      required: [true, "Reason of payment is required"],
    },
    invoice_url: {
      type: String,
      required: [true, "Invoice URL generated by Yaya is required"],
    },
    is_paid: { type: Boolean, default: false },
  },
  {
    writeConcern: {
      w: "majority",
      j: true,
    },
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Transaction model
const Transaction = mongoose.model("Transaction", txnSchema);

// Export the model
module.exports = Transaction;
